#!/usr/bin/env python3
from dotenv import load_dotenv
import os
import base64
from requests import post, get
import json
import token_get
import sys 

load_dotenv()

def search_for_artist(token, artist_name):
  url = "https://api.spotify.com/v1/search"
  headers = get_auth_header(token)
  query = f"?q={artist_name}&type=artist&limit=1"

  query_url = url + query
  result = get(query_url, headers=headers)
  json_result = json.loads(result.content)["artists"]["items"]
  if len(json_result) == 0:
    return None
  return json_result[0]

def handle_artist(f = sys.argv[1]):
  artist = f
  token = token_get.get_token() 
  result = search_for_artist(token, artist)
  with open("data/artist.json", "w") as f:
    json.dump(result, f)
  return