language: c
sudo: required
service: docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - bash -ex .travis-docker.sh
env:
  global:
    - PINS="spotify-web-api:."
    - PACKAGE=spotify-web-api
  matrix:
    - DISTRO="debian-9-ocaml-4.03"
    - DISTRO="debian-9-ocaml-4.04"
    - DISTRO="debian-9-ocaml-4.05"
    - DISTRO="debian-9-ocaml-4.06"
    - DISTRO="debian-9-ocaml-4.07"
